### ISSUE TITLE
Incompatible to PostgreSQL 10.X ?

### ISSUE THREAD

**Issue by neonsamurai** [deepstreamIO/deepstream.io-storage-postgres#21]
When using the latest version of PostgreSQL with the storage connector, the following error occurs on Deepstream startup:

```
 TypeError: Cannot read property 'splice' of null
     at Object.exports.checkVersion (/var/lib/deepstream/deepstream.io-storage-postgres/src/utils.js:51:5)
     at query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:367:13)
     at query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:367:13)
     at Result.client.query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:270:9)
     at Result.Query.handleReadyForQuery (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/query.js:144:10)
     at query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:367:13)
     at Result.client.query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:270:9)
     at Result.client.query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:270:9)
     at Result.Query.handleReadyForQuery (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/query.js:144:10)
     at Connection.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/client.js:180:19)
     at Result.client.query (/var/lib/deepstream/deepstream.io-storage-postgres/src/connector.js:270:9)
     at Result.Query.handleReadyForQuery (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/query.js:144:10)
     at Connection.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/client.js:180:19)
     at Connection.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/client.js:180:19)
     at emitOne (events.js:96:13)
     at Result.Query.handleReadyForQuery (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/query.js:144:10)
     at emitOne (events.js:96:13)
     at emitOne (events.js:96:13)
     at Connection.emit (events.js:188:7)
     at Connection.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/client.js:180:19)
     at emitOne (events.js:96:13)
     at Connection.emit (events.js:188:7)
     at Connection.emit (events.js:188:7)
     at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:133:12)
     at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:133:12)
     at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:133:12)
     at emitOne (events.js:96:13)
     at emitOne (events.js:96:13)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
     at Socket.emit (events.js:188:7)
     at Connection.emit (events.js:188:7)
     at Socket.emit (events.js:188:7)
     at Socket.<anonymous> (/var/lib/deepstream/deepstream.io-storage-postgres/node_modules/pg/lib/connection.js:133:12)
     at emitOne (events.js:96:13)
     at Socket.emit (events.js:188:7)
```

I looked at the code and I suspect that the SQL statement for database initialisation fails for some reason, thus the regex won't match anything returning null which will then raise an exception when invoking `splice(1)`

As a workaround I will use Postgres 9 (the error does not occur with version 9.x) for the time being.

**Comment by mhaagens** [comment]
Seconded. Will there be an update to the deepstream installer?

**Comment by mhaagens** [comment]
No news on fixing this?

**Comment by yasserf** [comment]
Just released a new version. Apologies for the (very) long delay
